// Code generated by ndn tlv codegen DO NOT EDIT.
package tlv

import (
	"encoding/binary"
	"io"
	"strings"

	enc "github.com/named-data/ndnd/std/encoding"
	spec "github.com/named-data/ndnd/std/ndn/spec_2022"
)

type RepoCmdEncoder struct {
	Length uint

	SyncJoin_encoder      SyncJoinEncoder
	SyncLeave_encoder     SyncLeaveEncoder
	BlobFetch_encoder     BlobFetchEncoder
	RepoCmdDelete_encoder RepoCmdDeleteEncoder
	RepoCmdInsert_encoder RepoCmdInsertEncoder
}

type RepoCmdParsingContext struct {
	SyncJoin_context      SyncJoinParsingContext
	SyncLeave_context     SyncLeaveParsingContext
	BlobFetch_context     BlobFetchParsingContext
	RepoCmdDelete_context RepoCmdDeleteParsingContext
	RepoCmdInsert_context RepoCmdInsertParsingContext
}

func (encoder *RepoCmdEncoder) Init(value *RepoCmd) {
	if value.SyncJoin != nil {
		encoder.SyncJoin_encoder.Init(value.SyncJoin)
	}
	if value.SyncLeave != nil {
		encoder.SyncLeave_encoder.Init(value.SyncLeave)
	}
	if value.BlobFetch != nil {
		encoder.BlobFetch_encoder.Init(value.BlobFetch)
	}
	if value.RepoCmdDelete != nil {
		encoder.RepoCmdDelete_encoder.Init(value.RepoCmdDelete)
	}
	if value.RepoCmdInsert != nil {
		encoder.RepoCmdInsert_encoder.Init(value.RepoCmdInsert)
	}

	l := uint(0)
	if value.SyncJoin != nil {
		l += 3
		l += uint(enc.TLNum(encoder.SyncJoin_encoder.Length).EncodingLength())
		l += encoder.SyncJoin_encoder.Length
	}
	if value.SyncLeave != nil {
		l += 3
		l += uint(enc.TLNum(encoder.SyncLeave_encoder.Length).EncodingLength())
		l += encoder.SyncLeave_encoder.Length
	}
	if value.BlobFetch != nil {
		l += 3
		l += uint(enc.TLNum(encoder.BlobFetch_encoder.Length).EncodingLength())
		l += encoder.BlobFetch_encoder.Length
	}
	if value.RepoCmdDelete != nil {
		l += 3
		l += uint(enc.TLNum(encoder.RepoCmdDelete_encoder.Length).EncodingLength())
		l += encoder.RepoCmdDelete_encoder.Length
	}
	if value.RepoCmdInsert != nil {
		l += 3
		l += uint(enc.TLNum(encoder.RepoCmdInsert_encoder.Length).EncodingLength())
		l += encoder.RepoCmdInsert_encoder.Length
	}
	encoder.Length = l

}

func (context *RepoCmdParsingContext) Init() {
	context.SyncJoin_context.Init()
	context.SyncLeave_context.Init()
	context.BlobFetch_context.Init()
	context.RepoCmdDelete_context.Init()
	context.RepoCmdInsert_context.Init()
}

func (encoder *RepoCmdEncoder) EncodeInto(value *RepoCmd, buf []byte) {

	pos := uint(0)

	if value.SyncJoin != nil {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(7600))
		pos += 3
		pos += uint(enc.TLNum(encoder.SyncJoin_encoder.Length).EncodeInto(buf[pos:]))
		if encoder.SyncJoin_encoder.Length > 0 {
			encoder.SyncJoin_encoder.EncodeInto(value.SyncJoin, buf[pos:])
			pos += encoder.SyncJoin_encoder.Length
		}
	}
	if value.SyncLeave != nil {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(7601))
		pos += 3
		pos += uint(enc.TLNum(encoder.SyncLeave_encoder.Length).EncodeInto(buf[pos:]))
		if encoder.SyncLeave_encoder.Length > 0 {
			encoder.SyncLeave_encoder.EncodeInto(value.SyncLeave, buf[pos:])
			pos += encoder.SyncLeave_encoder.Length
		}
	}
	if value.BlobFetch != nil {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(7602))
		pos += 3
		pos += uint(enc.TLNum(encoder.BlobFetch_encoder.Length).EncodeInto(buf[pos:]))
		if encoder.BlobFetch_encoder.Length > 0 {
			encoder.BlobFetch_encoder.EncodeInto(value.BlobFetch, buf[pos:])
			pos += encoder.BlobFetch_encoder.Length
		}
	}
	if value.RepoCmdDelete != nil {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(7603))
		pos += 3
		pos += uint(enc.TLNum(encoder.RepoCmdDelete_encoder.Length).EncodeInto(buf[pos:]))
		if encoder.RepoCmdDelete_encoder.Length > 0 {
			encoder.RepoCmdDelete_encoder.EncodeInto(value.RepoCmdDelete, buf[pos:])
			pos += encoder.RepoCmdDelete_encoder.Length
		}
	}
	if value.RepoCmdInsert != nil {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(7604))
		pos += 3
		pos += uint(enc.TLNum(encoder.RepoCmdInsert_encoder.Length).EncodeInto(buf[pos:]))
		if encoder.RepoCmdInsert_encoder.Length > 0 {
			encoder.RepoCmdInsert_encoder.EncodeInto(value.RepoCmdInsert, buf[pos:])
			pos += encoder.RepoCmdInsert_encoder.Length
		}
	}
}

func (encoder *RepoCmdEncoder) Encode(value *RepoCmd) enc.Wire {

	wire := make(enc.Wire, 1)
	wire[0] = make([]byte, encoder.Length)
	buf := wire[0]
	encoder.EncodeInto(value, buf)

	return wire
}

func (context *RepoCmdParsingContext) Parse(reader enc.WireView, ignoreCritical bool) (*RepoCmd, error) {

	var handled_SyncJoin bool = false
	var handled_SyncLeave bool = false
	var handled_BlobFetch bool = false
	var handled_RepoCmdDelete bool = false
	var handled_RepoCmdInsert bool = false

	progress := -1
	_ = progress

	value := &RepoCmd{}
	var err error
	var startPos int
	for {
		startPos = reader.Pos()
		if startPos >= reader.Length() {
			break
		}
		typ := enc.TLNum(0)
		l := enc.TLNum(0)
		typ, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}
		l, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}

		err = nil
		if handled := false; true {
			switch typ {
			case 7600:
				if true {
					handled = true
					handled_SyncJoin = true
					value.SyncJoin, err = context.SyncJoin_context.Parse(reader.Delegate(int(l)), ignoreCritical)
				}
			case 7601:
				if true {
					handled = true
					handled_SyncLeave = true
					value.SyncLeave, err = context.SyncLeave_context.Parse(reader.Delegate(int(l)), ignoreCritical)
				}
			case 7602:
				if true {
					handled = true
					handled_BlobFetch = true
					value.BlobFetch, err = context.BlobFetch_context.Parse(reader.Delegate(int(l)), ignoreCritical)
				}
			case 7603:
				if true {
					handled = true
					handled_RepoCmdDelete = true
					value.RepoCmdDelete, err = context.RepoCmdDelete_context.Parse(reader.Delegate(int(l)), ignoreCritical)
				}
			case 7604:
				if true {
					handled = true
					handled_RepoCmdInsert = true
					value.RepoCmdInsert, err = context.RepoCmdInsert_context.Parse(reader.Delegate(int(l)), ignoreCritical)
				}
			default:
				if !ignoreCritical && ((typ <= 31) || ((typ & 1) == 1)) {
					return nil, enc.ErrUnrecognizedField{TypeNum: typ}
				}
				handled = true
				err = reader.Skip(int(l))
			}
			if err == nil && !handled {
			}
			if err != nil {
				return nil, enc.ErrFailToParse{TypeNum: typ, Err: err}
			}
		}
	}

	startPos = reader.Pos()
	err = nil

	if !handled_SyncJoin && err == nil {
		value.SyncJoin = nil
	}
	if !handled_SyncLeave && err == nil {
		value.SyncLeave = nil
	}
	if !handled_BlobFetch && err == nil {
		value.BlobFetch = nil
	}
	if !handled_RepoCmdDelete && err == nil {
		value.RepoCmdDelete = nil
	}
	if !handled_RepoCmdInsert && err == nil {
		value.RepoCmdInsert = nil
	}

	if err != nil {
		return nil, err
	}

	return value, nil
}

func (value *RepoCmd) Encode() enc.Wire {
	encoder := RepoCmdEncoder{}
	encoder.Init(value)
	return encoder.Encode(value)
}

func (value *RepoCmd) Bytes() []byte {
	return value.Encode().Join()
}

func ParseRepoCmd(reader enc.WireView, ignoreCritical bool) (*RepoCmd, error) {
	context := RepoCmdParsingContext{}
	context.Init()
	return context.Parse(reader, ignoreCritical)
}

type RepoCmdResEncoder struct {
	Length uint
}

type RepoCmdResParsingContext struct {
}

func (encoder *RepoCmdResEncoder) Init(value *RepoCmdRes) {

	l := uint(0)
	l += 3
	l += uint(1 + enc.Nat(value.Status).EncodingLength())
	l += 3
	l += uint(enc.TLNum(len(value.Message)).EncodingLength())
	l += uint(len(value.Message))
	encoder.Length = l

}

func (context *RepoCmdResParsingContext) Init() {

}

func (encoder *RepoCmdResEncoder) EncodeInto(value *RepoCmdRes, buf []byte) {

	pos := uint(0)

	buf[pos] = 253
	binary.BigEndian.PutUint16(buf[pos+1:], uint16(657))
	pos += 3

	buf[pos] = byte(enc.Nat(value.Status).EncodeInto(buf[pos+1:]))
	pos += uint(1 + buf[pos])
	buf[pos] = 253
	binary.BigEndian.PutUint16(buf[pos+1:], uint16(658))
	pos += 3
	pos += uint(enc.TLNum(len(value.Message)).EncodeInto(buf[pos:]))
	copy(buf[pos:], value.Message)
	pos += uint(len(value.Message))
}

func (encoder *RepoCmdResEncoder) Encode(value *RepoCmdRes) enc.Wire {

	wire := make(enc.Wire, 1)
	wire[0] = make([]byte, encoder.Length)
	buf := wire[0]
	encoder.EncodeInto(value, buf)

	return wire
}

func (context *RepoCmdResParsingContext) Parse(reader enc.WireView, ignoreCritical bool) (*RepoCmdRes, error) {

	var handled_Status bool = false
	var handled_Message bool = false

	progress := -1
	_ = progress

	value := &RepoCmdRes{}
	var err error
	var startPos int
	for {
		startPos = reader.Pos()
		if startPos >= reader.Length() {
			break
		}
		typ := enc.TLNum(0)
		l := enc.TLNum(0)
		typ, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}
		l, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}

		err = nil
		if handled := false; true {
			switch typ {
			case 657:
				if true {
					handled = true
					handled_Status = true
					value.Status = uint64(0)
					{
						for i := 0; i < int(l); i++ {
							x := byte(0)
							x, err = reader.ReadByte()
							if err != nil {
								if err == io.EOF {
									err = io.ErrUnexpectedEOF
								}
								break
							}
							value.Status = uint64(value.Status<<8) | uint64(x)
						}
					}
				}
			case 658:
				if true {
					handled = true
					handled_Message = true
					{
						var builder strings.Builder
						_, err = reader.CopyN(&builder, int(l))
						if err == nil {
							value.Message = builder.String()
						}
					}
				}
			default:
				if !ignoreCritical && ((typ <= 31) || ((typ & 1) == 1)) {
					return nil, enc.ErrUnrecognizedField{TypeNum: typ}
				}
				handled = true
				err = reader.Skip(int(l))
			}
			if err == nil && !handled {
			}
			if err != nil {
				return nil, enc.ErrFailToParse{TypeNum: typ, Err: err}
			}
		}
	}

	startPos = reader.Pos()
	err = nil

	if !handled_Status && err == nil {
		err = enc.ErrSkipRequired{Name: "Status", TypeNum: 657}
	}
	if !handled_Message && err == nil {
		err = enc.ErrSkipRequired{Name: "Message", TypeNum: 658}
	}

	if err != nil {
		return nil, err
	}

	return value, nil
}

func (value *RepoCmdRes) Encode() enc.Wire {
	encoder := RepoCmdResEncoder{}
	encoder.Init(value)
	return encoder.Encode(value)
}

func (value *RepoCmdRes) Bytes() []byte {
	return value.Encode().Join()
}

func ParseRepoCmdRes(reader enc.WireView, ignoreCritical bool) (*RepoCmdRes, error) {
	context := RepoCmdResParsingContext{}
	context.Init()
	return context.Parse(reader, ignoreCritical)
}

type RepoCmdInsertEncoder struct {
	Length uint

	InterestName_encoder   spec.NameContainerEncoder
	ForwardingHint_encoder spec.NameContainerEncoder
}

type RepoCmdInsertParsingContext struct {
	InterestName_context   spec.NameContainerParsingContext
	ForwardingHint_context spec.NameContainerParsingContext
}

func (encoder *RepoCmdInsertEncoder) Init(value *RepoCmdInsert) {
	if value.InterestName != nil {
		encoder.InterestName_encoder.Init(value.InterestName)
	}
	if value.ForwardingHint != nil {
		encoder.ForwardingHint_encoder.Init(value.ForwardingHint)
	}

	l := uint(0)
	if value.InterestName != nil {
		l += 3
		l += uint(enc.TLNum(encoder.InterestName_encoder.Length).EncodingLength())
		l += encoder.InterestName_encoder.Length
	}
	if value.ForwardingHint != nil {
		l += 3
		l += uint(enc.TLNum(encoder.ForwardingHint_encoder.Length).EncodingLength())
		l += encoder.ForwardingHint_encoder.Length
	}
	encoder.Length = l

}

func (context *RepoCmdInsertParsingContext) Init() {
	context.InterestName_context.Init()
	context.ForwardingHint_context.Init()
}

func (encoder *RepoCmdInsertEncoder) EncodeInto(value *RepoCmdInsert, buf []byte) {

	pos := uint(0)

	if value.InterestName != nil {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(7605))
		pos += 3
		pos += uint(enc.TLNum(encoder.InterestName_encoder.Length).EncodeInto(buf[pos:]))
		if encoder.InterestName_encoder.Length > 0 {
			encoder.InterestName_encoder.EncodeInto(value.InterestName, buf[pos:])
			pos += encoder.InterestName_encoder.Length
		}
	}
	if value.ForwardingHint != nil {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(7606))
		pos += 3
		pos += uint(enc.TLNum(encoder.ForwardingHint_encoder.Length).EncodeInto(buf[pos:]))
		if encoder.ForwardingHint_encoder.Length > 0 {
			encoder.ForwardingHint_encoder.EncodeInto(value.ForwardingHint, buf[pos:])
			pos += encoder.ForwardingHint_encoder.Length
		}
	}
}

func (encoder *RepoCmdInsertEncoder) Encode(value *RepoCmdInsert) enc.Wire {

	wire := make(enc.Wire, 1)
	wire[0] = make([]byte, encoder.Length)
	buf := wire[0]
	encoder.EncodeInto(value, buf)

	return wire
}

func (context *RepoCmdInsertParsingContext) Parse(reader enc.WireView, ignoreCritical bool) (*RepoCmdInsert, error) {

	var handled_InterestName bool = false
	var handled_ForwardingHint bool = false

	progress := -1
	_ = progress

	value := &RepoCmdInsert{}
	var err error
	var startPos int
	for {
		startPos = reader.Pos()
		if startPos >= reader.Length() {
			break
		}
		typ := enc.TLNum(0)
		l := enc.TLNum(0)
		typ, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}
		l, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}

		err = nil
		if handled := false; true {
			switch typ {
			case 7605:
				if true {
					handled = true
					handled_InterestName = true
					value.InterestName, err = context.InterestName_context.Parse(reader.Delegate(int(l)), ignoreCritical)
				}
			case 7606:
				if true {
					handled = true
					handled_ForwardingHint = true
					value.ForwardingHint, err = context.ForwardingHint_context.Parse(reader.Delegate(int(l)), ignoreCritical)
				}
			default:
				if !ignoreCritical && ((typ <= 31) || ((typ & 1) == 1)) {
					return nil, enc.ErrUnrecognizedField{TypeNum: typ}
				}
				handled = true
				err = reader.Skip(int(l))
			}
			if err == nil && !handled {
			}
			if err != nil {
				return nil, enc.ErrFailToParse{TypeNum: typ, Err: err}
			}
		}
	}

	startPos = reader.Pos()
	err = nil

	if !handled_InterestName && err == nil {
		value.InterestName = nil
	}
	if !handled_ForwardingHint && err == nil {
		value.ForwardingHint = nil
	}

	if err != nil {
		return nil, err
	}

	return value, nil
}

func (value *RepoCmdInsert) Encode() enc.Wire {
	encoder := RepoCmdInsertEncoder{}
	encoder.Init(value)
	return encoder.Encode(value)
}

func (value *RepoCmdInsert) Bytes() []byte {
	return value.Encode().Join()
}

func ParseRepoCmdInsert(reader enc.WireView, ignoreCritical bool) (*RepoCmdInsert, error) {
	context := RepoCmdInsertParsingContext{}
	context.Init()
	return context.Parse(reader, ignoreCritical)
}

type RepoCmdDeleteEncoder struct {
	Length uint

	OwnerName_encoder spec.NameContainerEncoder
}

type RepoCmdDeleteParsingContext struct {
	OwnerName_context spec.NameContainerParsingContext
}

func (encoder *RepoCmdDeleteEncoder) Init(value *RepoCmdDelete) {

	if value.OwnerName != nil {
		encoder.OwnerName_encoder.Init(value.OwnerName)
	}

	l := uint(0)
	l += 3
	l += uint(enc.TLNum(len(value.FileName)).EncodingLength())
	l += uint(len(value.FileName))
	if value.OwnerName != nil {
		l += 3
		l += uint(enc.TLNum(encoder.OwnerName_encoder.Length).EncodingLength())
		l += encoder.OwnerName_encoder.Length
	}
	encoder.Length = l

}

func (context *RepoCmdDeleteParsingContext) Init() {

	context.OwnerName_context.Init()
}

func (encoder *RepoCmdDeleteEncoder) EncodeInto(value *RepoCmdDelete, buf []byte) {

	pos := uint(0)

	buf[pos] = 253
	binary.BigEndian.PutUint16(buf[pos+1:], uint16(7605))
	pos += 3
	pos += uint(enc.TLNum(len(value.FileName)).EncodeInto(buf[pos:]))
	copy(buf[pos:], value.FileName)
	pos += uint(len(value.FileName))
	if value.OwnerName != nil {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(7606))
		pos += 3
		pos += uint(enc.TLNum(encoder.OwnerName_encoder.Length).EncodeInto(buf[pos:]))
		if encoder.OwnerName_encoder.Length > 0 {
			encoder.OwnerName_encoder.EncodeInto(value.OwnerName, buf[pos:])
			pos += encoder.OwnerName_encoder.Length
		}
	}
}

func (encoder *RepoCmdDeleteEncoder) Encode(value *RepoCmdDelete) enc.Wire {

	wire := make(enc.Wire, 1)
	wire[0] = make([]byte, encoder.Length)
	buf := wire[0]
	encoder.EncodeInto(value, buf)

	return wire
}

func (context *RepoCmdDeleteParsingContext) Parse(reader enc.WireView, ignoreCritical bool) (*RepoCmdDelete, error) {

	var handled_FileName bool = false
	var handled_OwnerName bool = false

	progress := -1
	_ = progress

	value := &RepoCmdDelete{}
	var err error
	var startPos int
	for {
		startPos = reader.Pos()
		if startPos >= reader.Length() {
			break
		}
		typ := enc.TLNum(0)
		l := enc.TLNum(0)
		typ, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}
		l, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}

		err = nil
		if handled := false; true {
			switch typ {
			case 7605:
				if true {
					handled = true
					handled_FileName = true
					{
						var builder strings.Builder
						_, err = reader.CopyN(&builder, int(l))
						if err == nil {
							value.FileName = builder.String()
						}
					}
				}
			case 7606:
				if true {
					handled = true
					handled_OwnerName = true
					value.OwnerName, err = context.OwnerName_context.Parse(reader.Delegate(int(l)), ignoreCritical)
				}
			default:
				if !ignoreCritical && ((typ <= 31) || ((typ & 1) == 1)) {
					return nil, enc.ErrUnrecognizedField{TypeNum: typ}
				}
				handled = true
				err = reader.Skip(int(l))
			}
			if err == nil && !handled {
			}
			if err != nil {
				return nil, enc.ErrFailToParse{TypeNum: typ, Err: err}
			}
		}
	}

	startPos = reader.Pos()
	err = nil

	if !handled_FileName && err == nil {
		err = enc.ErrSkipRequired{Name: "FileName", TypeNum: 7605}
	}
	if !handled_OwnerName && err == nil {
		value.OwnerName = nil
	}

	if err != nil {
		return nil, err
	}

	return value, nil
}

func (value *RepoCmdDelete) Encode() enc.Wire {
	encoder := RepoCmdDeleteEncoder{}
	encoder.Init(value)
	return encoder.Encode(value)
}

func (value *RepoCmdDelete) Bytes() []byte {
	return value.Encode().Join()
}

func ParseRepoCmdDelete(reader enc.WireView, ignoreCritical bool) (*RepoCmdDelete, error) {
	context := RepoCmdDeleteParsingContext{}
	context.Init()
	return context.Parse(reader, ignoreCritical)
}

type SyncJoinEncoder struct {
	Length uint

	Protocol_encoder        spec.NameContainerEncoder
	Group_encoder           spec.NameContainerEncoder
	MulticastPrefix_encoder spec.NameContainerEncoder
	HistorySnapshot_encoder HistorySnapshotConfigEncoder
	SecurityConfig_encoder  spec.NameContainerEncoder
}

type SyncJoinParsingContext struct {
	Protocol_context        spec.NameContainerParsingContext
	Group_context           spec.NameContainerParsingContext
	MulticastPrefix_context spec.NameContainerParsingContext
	HistorySnapshot_context HistorySnapshotConfigParsingContext
	SecurityConfig_context  spec.NameContainerParsingContext
}

func (encoder *SyncJoinEncoder) Init(value *SyncJoin) {
	if value.Protocol != nil {
		encoder.Protocol_encoder.Init(value.Protocol)
	}
	if value.Group != nil {
		encoder.Group_encoder.Init(value.Group)
	}
	if value.MulticastPrefix != nil {
		encoder.MulticastPrefix_encoder.Init(value.MulticastPrefix)
	}
	if value.HistorySnapshot != nil {
		encoder.HistorySnapshot_encoder.Init(value.HistorySnapshot)
	}
	if value.SecurityConfig != nil {
		encoder.SecurityConfig_encoder.Init(value.SecurityConfig)
	}

	l := uint(0)
	if value.Protocol != nil {
		l += 3
		l += uint(enc.TLNum(encoder.Protocol_encoder.Length).EncodingLength())
		l += encoder.Protocol_encoder.Length
	}
	if value.Group != nil {
		l += 3
		l += uint(enc.TLNum(encoder.Group_encoder.Length).EncodingLength())
		l += encoder.Group_encoder.Length
	}
	if value.MulticastPrefix != nil {
		l += 3
		l += uint(enc.TLNum(encoder.MulticastPrefix_encoder.Length).EncodingLength())
		l += encoder.MulticastPrefix_encoder.Length
	}
	if value.HistorySnapshot != nil {
		l += 3
		l += uint(enc.TLNum(encoder.HistorySnapshot_encoder.Length).EncodingLength())
		l += encoder.HistorySnapshot_encoder.Length
	}
	if value.SecurityConfig != nil {
		l += 3
		l += uint(enc.TLNum(encoder.SecurityConfig_encoder.Length).EncodingLength())
		l += encoder.SecurityConfig_encoder.Length
	}
	encoder.Length = l

}

func (context *SyncJoinParsingContext) Init() {
	context.Protocol_context.Init()
	context.Group_context.Init()
	context.MulticastPrefix_context.Init()
	context.HistorySnapshot_context.Init()
	context.SecurityConfig_context.Init()
}

func (encoder *SyncJoinEncoder) EncodeInto(value *SyncJoin, buf []byte) {

	pos := uint(0)

	if value.Protocol != nil {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(401))
		pos += 3
		pos += uint(enc.TLNum(encoder.Protocol_encoder.Length).EncodeInto(buf[pos:]))
		if encoder.Protocol_encoder.Length > 0 {
			encoder.Protocol_encoder.EncodeInto(value.Protocol, buf[pos:])
			pos += encoder.Protocol_encoder.Length
		}
	}
	if value.Group != nil {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(403))
		pos += 3
		pos += uint(enc.TLNum(encoder.Group_encoder.Length).EncodeInto(buf[pos:]))
		if encoder.Group_encoder.Length > 0 {
			encoder.Group_encoder.EncodeInto(value.Group, buf[pos:])
			pos += encoder.Group_encoder.Length
		}
	}
	if value.MulticastPrefix != nil {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(404))
		pos += 3
		pos += uint(enc.TLNum(encoder.MulticastPrefix_encoder.Length).EncodeInto(buf[pos:]))
		if encoder.MulticastPrefix_encoder.Length > 0 {
			encoder.MulticastPrefix_encoder.EncodeInto(value.MulticastPrefix, buf[pos:])
			pos += encoder.MulticastPrefix_encoder.Length
		}
	}
	if value.HistorySnapshot != nil {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(420))
		pos += 3
		pos += uint(enc.TLNum(encoder.HistorySnapshot_encoder.Length).EncodeInto(buf[pos:]))
		if encoder.HistorySnapshot_encoder.Length > 0 {
			encoder.HistorySnapshot_encoder.EncodeInto(value.HistorySnapshot, buf[pos:])
			pos += encoder.HistorySnapshot_encoder.Length
		}
	}
	if value.SecurityConfig != nil {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(7604))
		pos += 3
		pos += uint(enc.TLNum(encoder.SecurityConfig_encoder.Length).EncodeInto(buf[pos:]))
		if encoder.SecurityConfig_encoder.Length > 0 {
			encoder.SecurityConfig_encoder.EncodeInto(value.SecurityConfig, buf[pos:])
			pos += encoder.SecurityConfig_encoder.Length
		}
	}
}

func (encoder *SyncJoinEncoder) Encode(value *SyncJoin) enc.Wire {

	wire := make(enc.Wire, 1)
	wire[0] = make([]byte, encoder.Length)
	buf := wire[0]
	encoder.EncodeInto(value, buf)

	return wire
}

func (context *SyncJoinParsingContext) Parse(reader enc.WireView, ignoreCritical bool) (*SyncJoin, error) {

	var handled_Protocol bool = false
	var handled_Group bool = false
	var handled_MulticastPrefix bool = false
	var handled_HistorySnapshot bool = false
	var handled_SecurityConfig bool = false

	progress := -1
	_ = progress

	value := &SyncJoin{}
	var err error
	var startPos int
	for {
		startPos = reader.Pos()
		if startPos >= reader.Length() {
			break
		}
		typ := enc.TLNum(0)
		l := enc.TLNum(0)
		typ, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}
		l, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}

		err = nil
		if handled := false; true {
			switch typ {
			case 401:
				if true {
					handled = true
					handled_Protocol = true
					value.Protocol, err = context.Protocol_context.Parse(reader.Delegate(int(l)), ignoreCritical)
				}
			case 403:
				if true {
					handled = true
					handled_Group = true
					value.Group, err = context.Group_context.Parse(reader.Delegate(int(l)), ignoreCritical)
				}
			case 404:
				if true {
					handled = true
					handled_MulticastPrefix = true
					value.MulticastPrefix, err = context.MulticastPrefix_context.Parse(reader.Delegate(int(l)), ignoreCritical)
				}
			case 420:
				if true {
					handled = true
					handled_HistorySnapshot = true
					value.HistorySnapshot, err = context.HistorySnapshot_context.Parse(reader.Delegate(int(l)), ignoreCritical)
				}
			case 7604:
				if true {
					handled = true
					handled_SecurityConfig = true
					value.SecurityConfig, err = context.SecurityConfig_context.Parse(reader.Delegate(int(l)), ignoreCritical)
				}
			default:
				if !ignoreCritical && ((typ <= 31) || ((typ & 1) == 1)) {
					return nil, enc.ErrUnrecognizedField{TypeNum: typ}
				}
				handled = true
				err = reader.Skip(int(l))
			}
			if err == nil && !handled {
			}
			if err != nil {
				return nil, enc.ErrFailToParse{TypeNum: typ, Err: err}
			}
		}
	}

	startPos = reader.Pos()
	err = nil

	if !handled_Protocol && err == nil {
		value.Protocol = nil
	}
	if !handled_Group && err == nil {
		value.Group = nil
	}
	if !handled_MulticastPrefix && err == nil {
		value.MulticastPrefix = nil
	}
	if !handled_HistorySnapshot && err == nil {
		value.HistorySnapshot = nil
	}
	if !handled_SecurityConfig && err == nil {
		value.SecurityConfig = nil
	}

	if err != nil {
		return nil, err
	}

	return value, nil
}

func (value *SyncJoin) Encode() enc.Wire {
	encoder := SyncJoinEncoder{}
	encoder.Init(value)
	return encoder.Encode(value)
}

func (value *SyncJoin) Bytes() []byte {
	return value.Encode().Join()
}

func ParseSyncJoin(reader enc.WireView, ignoreCritical bool) (*SyncJoin, error) {
	context := SyncJoinParsingContext{}
	context.Init()
	return context.Parse(reader, ignoreCritical)
}

type SyncLeaveEncoder struct {
	Length uint

	Protocol_encoder spec.NameContainerEncoder
	Group_encoder    spec.NameContainerEncoder
}

type SyncLeaveParsingContext struct {
	Protocol_context spec.NameContainerParsingContext
	Group_context    spec.NameContainerParsingContext
}

func (encoder *SyncLeaveEncoder) Init(value *SyncLeave) {
	if value.Protocol != nil {
		encoder.Protocol_encoder.Init(value.Protocol)
	}
	if value.Group != nil {
		encoder.Group_encoder.Init(value.Group)
	}

	l := uint(0)
	if value.Protocol != nil {
		l += 3
		l += uint(enc.TLNum(encoder.Protocol_encoder.Length).EncodingLength())
		l += encoder.Protocol_encoder.Length
	}
	if value.Group != nil {
		l += 3
		l += uint(enc.TLNum(encoder.Group_encoder.Length).EncodingLength())
		l += encoder.Group_encoder.Length
	}
	encoder.Length = l

}

func (context *SyncLeaveParsingContext) Init() {
	context.Protocol_context.Init()
	context.Group_context.Init()
}

func (encoder *SyncLeaveEncoder) EncodeInto(value *SyncLeave, buf []byte) {

	pos := uint(0)

	if value.Protocol != nil {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(401))
		pos += 3
		pos += uint(enc.TLNum(encoder.Protocol_encoder.Length).EncodeInto(buf[pos:]))
		if encoder.Protocol_encoder.Length > 0 {
			encoder.Protocol_encoder.EncodeInto(value.Protocol, buf[pos:])
			pos += encoder.Protocol_encoder.Length
		}
	}
	if value.Group != nil {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(403))
		pos += 3
		pos += uint(enc.TLNum(encoder.Group_encoder.Length).EncodeInto(buf[pos:]))
		if encoder.Group_encoder.Length > 0 {
			encoder.Group_encoder.EncodeInto(value.Group, buf[pos:])
			pos += encoder.Group_encoder.Length
		}
	}
}

func (encoder *SyncLeaveEncoder) Encode(value *SyncLeave) enc.Wire {

	wire := make(enc.Wire, 1)
	wire[0] = make([]byte, encoder.Length)
	buf := wire[0]
	encoder.EncodeInto(value, buf)

	return wire
}

func (context *SyncLeaveParsingContext) Parse(reader enc.WireView, ignoreCritical bool) (*SyncLeave, error) {

	var handled_Protocol bool = false
	var handled_Group bool = false

	progress := -1
	_ = progress

	value := &SyncLeave{}
	var err error
	var startPos int
	for {
		startPos = reader.Pos()
		if startPos >= reader.Length() {
			break
		}
		typ := enc.TLNum(0)
		l := enc.TLNum(0)
		typ, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}
		l, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}

		err = nil
		if handled := false; true {
			switch typ {
			case 401:
				if true {
					handled = true
					handled_Protocol = true
					value.Protocol, err = context.Protocol_context.Parse(reader.Delegate(int(l)), ignoreCritical)
				}
			case 403:
				if true {
					handled = true
					handled_Group = true
					value.Group, err = context.Group_context.Parse(reader.Delegate(int(l)), ignoreCritical)
				}
			default:
				if !ignoreCritical && ((typ <= 31) || ((typ & 1) == 1)) {
					return nil, enc.ErrUnrecognizedField{TypeNum: typ}
				}
				handled = true
				err = reader.Skip(int(l))
			}
			if err == nil && !handled {
			}
			if err != nil {
				return nil, enc.ErrFailToParse{TypeNum: typ, Err: err}
			}
		}
	}

	startPos = reader.Pos()
	err = nil

	if !handled_Protocol && err == nil {
		value.Protocol = nil
	}
	if !handled_Group && err == nil {
		value.Group = nil
	}

	if err != nil {
		return nil, err
	}

	return value, nil
}

func (value *SyncLeave) Encode() enc.Wire {
	encoder := SyncLeaveEncoder{}
	encoder.Init(value)
	return encoder.Encode(value)
}

func (value *SyncLeave) Bytes() []byte {
	return value.Encode().Join()
}

func ParseSyncLeave(reader enc.WireView, ignoreCritical bool) (*SyncLeave, error) {
	context := SyncLeaveParsingContext{}
	context.Init()
	return context.Parse(reader, ignoreCritical)
}

type HistorySnapshotConfigEncoder struct {
	Length uint
}

type HistorySnapshotConfigParsingContext struct {
}

func (encoder *HistorySnapshotConfigEncoder) Init(value *HistorySnapshotConfig) {

	l := uint(0)
	l += 3
	l += uint(1 + enc.Nat(value.Threshold).EncodingLength())
	encoder.Length = l

}

func (context *HistorySnapshotConfigParsingContext) Init() {

}

func (encoder *HistorySnapshotConfigEncoder) EncodeInto(value *HistorySnapshotConfig, buf []byte) {

	pos := uint(0)

	buf[pos] = 253
	binary.BigEndian.PutUint16(buf[pos+1:], uint16(421))
	pos += 3

	buf[pos] = byte(enc.Nat(value.Threshold).EncodeInto(buf[pos+1:]))
	pos += uint(1 + buf[pos])
}

func (encoder *HistorySnapshotConfigEncoder) Encode(value *HistorySnapshotConfig) enc.Wire {

	wire := make(enc.Wire, 1)
	wire[0] = make([]byte, encoder.Length)
	buf := wire[0]
	encoder.EncodeInto(value, buf)

	return wire
}

func (context *HistorySnapshotConfigParsingContext) Parse(reader enc.WireView, ignoreCritical bool) (*HistorySnapshotConfig, error) {

	var handled_Threshold bool = false

	progress := -1
	_ = progress

	value := &HistorySnapshotConfig{}
	var err error
	var startPos int
	for {
		startPos = reader.Pos()
		if startPos >= reader.Length() {
			break
		}
		typ := enc.TLNum(0)
		l := enc.TLNum(0)
		typ, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}
		l, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}

		err = nil
		if handled := false; true {
			switch typ {
			case 421:
				if true {
					handled = true
					handled_Threshold = true
					value.Threshold = uint64(0)
					{
						for i := 0; i < int(l); i++ {
							x := byte(0)
							x, err = reader.ReadByte()
							if err != nil {
								if err == io.EOF {
									err = io.ErrUnexpectedEOF
								}
								break
							}
							value.Threshold = uint64(value.Threshold<<8) | uint64(x)
						}
					}
				}
			default:
				if !ignoreCritical && ((typ <= 31) || ((typ & 1) == 1)) {
					return nil, enc.ErrUnrecognizedField{TypeNum: typ}
				}
				handled = true
				err = reader.Skip(int(l))
			}
			if err == nil && !handled {
			}
			if err != nil {
				return nil, enc.ErrFailToParse{TypeNum: typ, Err: err}
			}
		}
	}

	startPos = reader.Pos()
	err = nil

	if !handled_Threshold && err == nil {
		err = enc.ErrSkipRequired{Name: "Threshold", TypeNum: 421}
	}

	if err != nil {
		return nil, err
	}

	return value, nil
}

func (value *HistorySnapshotConfig) Encode() enc.Wire {
	encoder := HistorySnapshotConfigEncoder{}
	encoder.Init(value)
	return encoder.Encode(value)
}

func (value *HistorySnapshotConfig) Bytes() []byte {
	return value.Encode().Join()
}

func ParseHistorySnapshotConfig(reader enc.WireView, ignoreCritical bool) (*HistorySnapshotConfig, error) {
	context := HistorySnapshotConfigParsingContext{}
	context.Init()
	return context.Parse(reader, ignoreCritical)
}

type BlobFetchEncoder struct {
	Length uint

	Name_encoder    spec.NameContainerEncoder
	Data_subencoder []struct {
	}
}

type BlobFetchParsingContext struct {
	Name_context spec.NameContainerParsingContext
}

func (encoder *BlobFetchEncoder) Init(value *BlobFetch) {
	if value.Name != nil {
		encoder.Name_encoder.Init(value.Name)
	}
	{
		Data_l := len(value.Data)
		encoder.Data_subencoder = make([]struct {
		}, Data_l)
		for i := 0; i < Data_l; i++ {
			pseudoEncoder := &encoder.Data_subencoder[i]
			pseudoValue := struct {
				Data []byte
			}{
				Data: value.Data[i],
			}
			{
				encoder := pseudoEncoder
				value := &pseudoValue

				_ = encoder
				_ = value
			}
		}
	}

	l := uint(0)
	if value.Name != nil {
		l += 3
		l += uint(enc.TLNum(encoder.Name_encoder.Length).EncodingLength())
		l += encoder.Name_encoder.Length
	}
	if value.Data != nil {
		for seq_i, seq_v := range value.Data {
			pseudoEncoder := &encoder.Data_subencoder[seq_i]
			pseudoValue := struct {
				Data []byte
			}{
				Data: seq_v,
			}
			{
				encoder := pseudoEncoder
				value := &pseudoValue
				if value.Data != nil {
					l += 3
					l += uint(enc.TLNum(len(value.Data)).EncodingLength())
					l += uint(len(value.Data))
				}
				_ = encoder
				_ = value
			}
		}
	}
	encoder.Length = l

}

func (context *BlobFetchParsingContext) Init() {
	context.Name_context.Init()

}

func (encoder *BlobFetchEncoder) EncodeInto(value *BlobFetch, buf []byte) {

	pos := uint(0)

	if value.Name != nil {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(440))
		pos += 3
		pos += uint(enc.TLNum(encoder.Name_encoder.Length).EncodeInto(buf[pos:]))
		if encoder.Name_encoder.Length > 0 {
			encoder.Name_encoder.EncodeInto(value.Name, buf[pos:])
			pos += encoder.Name_encoder.Length
		}
	}
	if value.Data != nil {
		for seq_i, seq_v := range value.Data {
			pseudoEncoder := &encoder.Data_subencoder[seq_i]
			pseudoValue := struct {
				Data []byte
			}{
				Data: seq_v,
			}
			{
				encoder := pseudoEncoder
				value := &pseudoValue
				if value.Data != nil {
					buf[pos] = 253
					binary.BigEndian.PutUint16(buf[pos+1:], uint16(442))
					pos += 3
					pos += uint(enc.TLNum(len(value.Data)).EncodeInto(buf[pos:]))
					copy(buf[pos:], value.Data)
					pos += uint(len(value.Data))
				}
				_ = encoder
				_ = value
			}
		}
	}
}

func (encoder *BlobFetchEncoder) Encode(value *BlobFetch) enc.Wire {

	wire := make(enc.Wire, 1)
	wire[0] = make([]byte, encoder.Length)
	buf := wire[0]
	encoder.EncodeInto(value, buf)

	return wire
}

func (context *BlobFetchParsingContext) Parse(reader enc.WireView, ignoreCritical bool) (*BlobFetch, error) {

	var handled_Name bool = false
	var handled_Data bool = false

	progress := -1
	_ = progress

	value := &BlobFetch{}
	var err error
	var startPos int
	for {
		startPos = reader.Pos()
		if startPos >= reader.Length() {
			break
		}
		typ := enc.TLNum(0)
		l := enc.TLNum(0)
		typ, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}
		l, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}

		err = nil
		if handled := false; true {
			switch typ {
			case 440:
				if true {
					handled = true
					handled_Name = true
					value.Name, err = context.Name_context.Parse(reader.Delegate(int(l)), ignoreCritical)
				}
			case 442:
				if true {
					handled = true
					handled_Data = true
					if value.Data == nil {
						value.Data = make([][]byte, 0)
					}
					{
						pseudoValue := struct {
							Data []byte
						}{}
						{
							value := &pseudoValue
							value.Data = make([]byte, l)
							_, err = reader.ReadFull(value.Data)
							_ = value
						}
						value.Data = append(value.Data, pseudoValue.Data)
					}
					progress--
				}
			default:
				if !ignoreCritical && ((typ <= 31) || ((typ & 1) == 1)) {
					return nil, enc.ErrUnrecognizedField{TypeNum: typ}
				}
				handled = true
				err = reader.Skip(int(l))
			}
			if err == nil && !handled {
			}
			if err != nil {
				return nil, enc.ErrFailToParse{TypeNum: typ, Err: err}
			}
		}
	}

	startPos = reader.Pos()
	err = nil

	if !handled_Name && err == nil {
		value.Name = nil
	}
	if !handled_Data && err == nil {
		// sequence - skip
	}

	if err != nil {
		return nil, err
	}

	return value, nil
}

func (value *BlobFetch) Encode() enc.Wire {
	encoder := BlobFetchEncoder{}
	encoder.Init(value)
	return encoder.Encode(value)
}

func (value *BlobFetch) Bytes() []byte {
	return value.Encode().Join()
}

func ParseBlobFetch(reader enc.WireView, ignoreCritical bool) (*BlobFetch, error) {
	context := BlobFetchParsingContext{}
	context.Init()
	return context.Parse(reader, ignoreCritical)
}

type SecurityConfigObjectEncoder struct {
	Length uint

	Anchors_subencoder []struct {
	}
}

type SecurityConfigObjectParsingContext struct {
}

func (encoder *SecurityConfigObjectEncoder) Init(value *SecurityConfigObject) {

	{
		Anchors_l := len(value.Anchors)
		encoder.Anchors_subencoder = make([]struct {
		}, Anchors_l)
		for i := 0; i < Anchors_l; i++ {
			pseudoEncoder := &encoder.Anchors_subencoder[i]
			pseudoValue := struct {
				Anchors []byte
			}{
				Anchors: value.Anchors[i],
			}
			{
				encoder := pseudoEncoder
				value := &pseudoValue

				_ = encoder
				_ = value
			}
		}
	}

	l := uint(0)
	if value.Schema != nil {
		l += 3
		l += uint(enc.TLNum(len(value.Schema)).EncodingLength())
		l += uint(len(value.Schema))
	}
	if value.Anchors != nil {
		for seq_i, seq_v := range value.Anchors {
			pseudoEncoder := &encoder.Anchors_subencoder[seq_i]
			pseudoValue := struct {
				Anchors []byte
			}{
				Anchors: seq_v,
			}
			{
				encoder := pseudoEncoder
				value := &pseudoValue
				if value.Anchors != nil {
					l += 3
					l += uint(enc.TLNum(len(value.Anchors)).EncodingLength())
					l += uint(len(value.Anchors))
				}
				_ = encoder
				_ = value
			}
		}
	}
	encoder.Length = l

}

func (context *SecurityConfigObjectParsingContext) Init() {

}

func (encoder *SecurityConfigObjectEncoder) EncodeInto(value *SecurityConfigObject, buf []byte) {

	pos := uint(0)

	if value.Schema != nil {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(421))
		pos += 3
		pos += uint(enc.TLNum(len(value.Schema)).EncodeInto(buf[pos:]))
		copy(buf[pos:], value.Schema)
		pos += uint(len(value.Schema))
	}
	if value.Anchors != nil {
		for seq_i, seq_v := range value.Anchors {
			pseudoEncoder := &encoder.Anchors_subencoder[seq_i]
			pseudoValue := struct {
				Anchors []byte
			}{
				Anchors: seq_v,
			}
			{
				encoder := pseudoEncoder
				value := &pseudoValue
				if value.Anchors != nil {
					buf[pos] = 253
					binary.BigEndian.PutUint16(buf[pos+1:], uint16(442))
					pos += 3
					pos += uint(enc.TLNum(len(value.Anchors)).EncodeInto(buf[pos:]))
					copy(buf[pos:], value.Anchors)
					pos += uint(len(value.Anchors))
				}
				_ = encoder
				_ = value
			}
		}
	}
}

func (encoder *SecurityConfigObjectEncoder) Encode(value *SecurityConfigObject) enc.Wire {

	wire := make(enc.Wire, 1)
	wire[0] = make([]byte, encoder.Length)
	buf := wire[0]
	encoder.EncodeInto(value, buf)

	return wire
}

func (context *SecurityConfigObjectParsingContext) Parse(reader enc.WireView, ignoreCritical bool) (*SecurityConfigObject, error) {

	var handled_Schema bool = false
	var handled_Anchors bool = false

	progress := -1
	_ = progress

	value := &SecurityConfigObject{}
	var err error
	var startPos int
	for {
		startPos = reader.Pos()
		if startPos >= reader.Length() {
			break
		}
		typ := enc.TLNum(0)
		l := enc.TLNum(0)
		typ, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}
		l, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}

		err = nil
		if handled := false; true {
			switch typ {
			case 421:
				if true {
					handled = true
					handled_Schema = true
					value.Schema = make([]byte, l)
					_, err = reader.ReadFull(value.Schema)
				}
			case 442:
				if true {
					handled = true
					handled_Anchors = true
					if value.Anchors == nil {
						value.Anchors = make([][]byte, 0)
					}
					{
						pseudoValue := struct {
							Anchors []byte
						}{}
						{
							value := &pseudoValue
							value.Anchors = make([]byte, l)
							_, err = reader.ReadFull(value.Anchors)
							_ = value
						}
						value.Anchors = append(value.Anchors, pseudoValue.Anchors)
					}
					progress--
				}
			default:
				if !ignoreCritical && ((typ <= 31) || ((typ & 1) == 1)) {
					return nil, enc.ErrUnrecognizedField{TypeNum: typ}
				}
				handled = true
				err = reader.Skip(int(l))
			}
			if err == nil && !handled {
			}
			if err != nil {
				return nil, enc.ErrFailToParse{TypeNum: typ, Err: err}
			}
		}
	}

	startPos = reader.Pos()
	err = nil

	if !handled_Schema && err == nil {
		value.Schema = nil
	}
	if !handled_Anchors && err == nil {
		// sequence - skip
	}

	if err != nil {
		return nil, err
	}

	return value, nil
}

func (value *SecurityConfigObject) Encode() enc.Wire {
	encoder := SecurityConfigObjectEncoder{}
	encoder.Init(value)
	return encoder.Encode(value)
}

func (value *SecurityConfigObject) Bytes() []byte {
	return value.Encode().Join()
}

func ParseSecurityConfigObject(reader enc.WireView, ignoreCritical bool) (*SecurityConfigObject, error) {
	context := SecurityConfigObjectParsingContext{}
	context.Init()
	return context.Parse(reader, ignoreCritical)
}

type CatalogCmdEncoder struct {
	Length uint

	GetFileInfo_encoder CatalogGetFileInfoEncoder
	Insert_encoder      CatalogEntryEncoder
	Delete_encoder      CatalogEntryEncoder
}

type CatalogCmdParsingContext struct {
	GetFileInfo_context CatalogGetFileInfoParsingContext
	Insert_context      CatalogEntryParsingContext
	Delete_context      CatalogEntryParsingContext
}

func (encoder *CatalogCmdEncoder) Init(value *CatalogCmd) {
	if value.GetFileInfo != nil {
		encoder.GetFileInfo_encoder.Init(value.GetFileInfo)
	}
	if value.Insert != nil {
		encoder.Insert_encoder.Init(value.Insert)
	}
	if value.Delete != nil {
		encoder.Delete_encoder.Init(value.Delete)
	}

	l := uint(0)
	if value.GetFileInfo != nil {
		l += 3
		l += uint(enc.TLNum(encoder.GetFileInfo_encoder.Length).EncodingLength())
		l += encoder.GetFileInfo_encoder.Length
	}
	if value.Insert != nil {
		l += 3
		l += uint(enc.TLNum(encoder.Insert_encoder.Length).EncodingLength())
		l += encoder.Insert_encoder.Length
	}
	if value.Delete != nil {
		l += 3
		l += uint(enc.TLNum(encoder.Delete_encoder.Length).EncodingLength())
		l += encoder.Delete_encoder.Length
	}
	encoder.Length = l

}

func (context *CatalogCmdParsingContext) Init() {
	context.GetFileInfo_context.Init()
	context.Insert_context.Init()
	context.Delete_context.Init()
}

func (encoder *CatalogCmdEncoder) EncodeInto(value *CatalogCmd, buf []byte) {

	pos := uint(0)

	if value.GetFileInfo != nil {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(7680))
		pos += 3
		pos += uint(enc.TLNum(encoder.GetFileInfo_encoder.Length).EncodeInto(buf[pos:]))
		if encoder.GetFileInfo_encoder.Length > 0 {
			encoder.GetFileInfo_encoder.EncodeInto(value.GetFileInfo, buf[pos:])
			pos += encoder.GetFileInfo_encoder.Length
		}
	}
	if value.Insert != nil {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(7681))
		pos += 3
		pos += uint(enc.TLNum(encoder.Insert_encoder.Length).EncodeInto(buf[pos:]))
		if encoder.Insert_encoder.Length > 0 {
			encoder.Insert_encoder.EncodeInto(value.Insert, buf[pos:])
			pos += encoder.Insert_encoder.Length
		}
	}
	if value.Delete != nil {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(7682))
		pos += 3
		pos += uint(enc.TLNum(encoder.Delete_encoder.Length).EncodeInto(buf[pos:]))
		if encoder.Delete_encoder.Length > 0 {
			encoder.Delete_encoder.EncodeInto(value.Delete, buf[pos:])
			pos += encoder.Delete_encoder.Length
		}
	}
}

func (encoder *CatalogCmdEncoder) Encode(value *CatalogCmd) enc.Wire {

	wire := make(enc.Wire, 1)
	wire[0] = make([]byte, encoder.Length)
	buf := wire[0]
	encoder.EncodeInto(value, buf)

	return wire
}

func (context *CatalogCmdParsingContext) Parse(reader enc.WireView, ignoreCritical bool) (*CatalogCmd, error) {

	var handled_GetFileInfo bool = false
	var handled_Insert bool = false
	var handled_Delete bool = false

	progress := -1
	_ = progress

	value := &CatalogCmd{}
	var err error
	var startPos int
	for {
		startPos = reader.Pos()
		if startPos >= reader.Length() {
			break
		}
		typ := enc.TLNum(0)
		l := enc.TLNum(0)
		typ, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}
		l, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}

		err = nil
		if handled := false; true {
			switch typ {
			case 7680:
				if true {
					handled = true
					handled_GetFileInfo = true
					value.GetFileInfo, err = context.GetFileInfo_context.Parse(reader.Delegate(int(l)), ignoreCritical)
				}
			case 7681:
				if true {
					handled = true
					handled_Insert = true
					value.Insert, err = context.Insert_context.Parse(reader.Delegate(int(l)), ignoreCritical)
				}
			case 7682:
				if true {
					handled = true
					handled_Delete = true
					value.Delete, err = context.Delete_context.Parse(reader.Delegate(int(l)), ignoreCritical)
				}
			default:
				if !ignoreCritical && ((typ <= 31) || ((typ & 1) == 1)) {
					return nil, enc.ErrUnrecognizedField{TypeNum: typ}
				}
				handled = true
				err = reader.Skip(int(l))
			}
			if err == nil && !handled {
			}
			if err != nil {
				return nil, enc.ErrFailToParse{TypeNum: typ, Err: err}
			}
		}
	}

	startPos = reader.Pos()
	err = nil

	if !handled_GetFileInfo && err == nil {
		value.GetFileInfo = nil
	}
	if !handled_Insert && err == nil {
		value.Insert = nil
	}
	if !handled_Delete && err == nil {
		value.Delete = nil
	}

	if err != nil {
		return nil, err
	}

	return value, nil
}

func (value *CatalogCmd) Encode() enc.Wire {
	encoder := CatalogCmdEncoder{}
	encoder.Init(value)
	return encoder.Encode(value)
}

func (value *CatalogCmd) Bytes() []byte {
	return value.Encode().Join()
}

func ParseCatalogCmd(reader enc.WireView, ignoreCritical bool) (*CatalogCmd, error) {
	context := CatalogCmdParsingContext{}
	context.Init()
	return context.Parse(reader, ignoreCritical)
}

type CatalogGetFileInfoEncoder struct {
	Length uint

	OwnerName_encoder spec.NameContainerEncoder
}

type CatalogGetFileInfoParsingContext struct {
	OwnerName_context spec.NameContainerParsingContext
}

func (encoder *CatalogGetFileInfoEncoder) Init(value *CatalogGetFileInfo) {

	if value.OwnerName != nil {
		encoder.OwnerName_encoder.Init(value.OwnerName)
	}

	l := uint(0)
	l += 3
	l += uint(enc.TLNum(len(value.FileName)).EncodingLength())
	l += uint(len(value.FileName))
	if value.OwnerName != nil {
		l += 3
		l += uint(enc.TLNum(encoder.OwnerName_encoder.Length).EncodingLength())
		l += encoder.OwnerName_encoder.Length
	}
	encoder.Length = l

}

func (context *CatalogGetFileInfoParsingContext) Init() {

	context.OwnerName_context.Init()
}

func (encoder *CatalogGetFileInfoEncoder) EncodeInto(value *CatalogGetFileInfo, buf []byte) {

	pos := uint(0)

	buf[pos] = 253
	binary.BigEndian.PutUint16(buf[pos+1:], uint16(7680))
	pos += 3
	pos += uint(enc.TLNum(len(value.FileName)).EncodeInto(buf[pos:]))
	copy(buf[pos:], value.FileName)
	pos += uint(len(value.FileName))
	if value.OwnerName != nil {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(7681))
		pos += 3
		pos += uint(enc.TLNum(encoder.OwnerName_encoder.Length).EncodeInto(buf[pos:]))
		if encoder.OwnerName_encoder.Length > 0 {
			encoder.OwnerName_encoder.EncodeInto(value.OwnerName, buf[pos:])
			pos += encoder.OwnerName_encoder.Length
		}
	}
}

func (encoder *CatalogGetFileInfoEncoder) Encode(value *CatalogGetFileInfo) enc.Wire {

	wire := make(enc.Wire, 1)
	wire[0] = make([]byte, encoder.Length)
	buf := wire[0]
	encoder.EncodeInto(value, buf)

	return wire
}

func (context *CatalogGetFileInfoParsingContext) Parse(reader enc.WireView, ignoreCritical bool) (*CatalogGetFileInfo, error) {

	var handled_FileName bool = false
	var handled_OwnerName bool = false

	progress := -1
	_ = progress

	value := &CatalogGetFileInfo{}
	var err error
	var startPos int
	for {
		startPos = reader.Pos()
		if startPos >= reader.Length() {
			break
		}
		typ := enc.TLNum(0)
		l := enc.TLNum(0)
		typ, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}
		l, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}

		err = nil
		if handled := false; true {
			switch typ {
			case 7680:
				if true {
					handled = true
					handled_FileName = true
					{
						var builder strings.Builder
						_, err = reader.CopyN(&builder, int(l))
						if err == nil {
							value.FileName = builder.String()
						}
					}
				}
			case 7681:
				if true {
					handled = true
					handled_OwnerName = true
					value.OwnerName, err = context.OwnerName_context.Parse(reader.Delegate(int(l)), ignoreCritical)
				}
			default:
				if !ignoreCritical && ((typ <= 31) || ((typ & 1) == 1)) {
					return nil, enc.ErrUnrecognizedField{TypeNum: typ}
				}
				handled = true
				err = reader.Skip(int(l))
			}
			if err == nil && !handled {
			}
			if err != nil {
				return nil, enc.ErrFailToParse{TypeNum: typ, Err: err}
			}
		}
	}

	startPos = reader.Pos()
	err = nil

	if !handled_FileName && err == nil {
		err = enc.ErrSkipRequired{Name: "FileName", TypeNum: 7680}
	}
	if !handled_OwnerName && err == nil {
		value.OwnerName = nil
	}

	if err != nil {
		return nil, err
	}

	return value, nil
}

func (value *CatalogGetFileInfo) Encode() enc.Wire {
	encoder := CatalogGetFileInfoEncoder{}
	encoder.Init(value)
	return encoder.Encode(value)
}

func (value *CatalogGetFileInfo) Bytes() []byte {
	return value.Encode().Join()
}

func ParseCatalogGetFileInfo(reader enc.WireView, ignoreCritical bool) (*CatalogGetFileInfo, error) {
	context := CatalogGetFileInfoParsingContext{}
	context.Init()
	return context.Parse(reader, ignoreCritical)
}

type CatalogEntryEncoder struct {
	Length uint

	OwnerName_encoder  spec.NameContainerEncoder
	ServerName_encoder spec.NameContainerEncoder
}

type CatalogEntryParsingContext struct {
	OwnerName_context  spec.NameContainerParsingContext
	ServerName_context spec.NameContainerParsingContext
}

func (encoder *CatalogEntryEncoder) Init(value *CatalogEntry) {

	if value.OwnerName != nil {
		encoder.OwnerName_encoder.Init(value.OwnerName)
	}
	if value.ServerName != nil {
		encoder.ServerName_encoder.Init(value.ServerName)
	}

	l := uint(0)
	l += 3
	l += uint(enc.TLNum(len(value.FileName)).EncodingLength())
	l += uint(len(value.FileName))
	if value.OwnerName != nil {
		l += 3
		l += uint(enc.TLNum(encoder.OwnerName_encoder.Length).EncodingLength())
		l += encoder.OwnerName_encoder.Length
	}
	if value.ServerName != nil {
		l += 3
		l += uint(enc.TLNum(encoder.ServerName_encoder.Length).EncodingLength())
		l += encoder.ServerName_encoder.Length
	}
	encoder.Length = l

}

func (context *CatalogEntryParsingContext) Init() {

	context.OwnerName_context.Init()
	context.ServerName_context.Init()
}

func (encoder *CatalogEntryEncoder) EncodeInto(value *CatalogEntry, buf []byte) {

	pos := uint(0)

	buf[pos] = 253
	binary.BigEndian.PutUint16(buf[pos+1:], uint16(7685))
	pos += 3
	pos += uint(enc.TLNum(len(value.FileName)).EncodeInto(buf[pos:]))
	copy(buf[pos:], value.FileName)
	pos += uint(len(value.FileName))
	if value.OwnerName != nil {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(7686))
		pos += 3
		pos += uint(enc.TLNum(encoder.OwnerName_encoder.Length).EncodeInto(buf[pos:]))
		if encoder.OwnerName_encoder.Length > 0 {
			encoder.OwnerName_encoder.EncodeInto(value.OwnerName, buf[pos:])
			pos += encoder.OwnerName_encoder.Length
		}
	}
	if value.ServerName != nil {
		buf[pos] = 253
		binary.BigEndian.PutUint16(buf[pos+1:], uint16(7687))
		pos += 3
		pos += uint(enc.TLNum(encoder.ServerName_encoder.Length).EncodeInto(buf[pos:]))
		if encoder.ServerName_encoder.Length > 0 {
			encoder.ServerName_encoder.EncodeInto(value.ServerName, buf[pos:])
			pos += encoder.ServerName_encoder.Length
		}
	}
}

func (encoder *CatalogEntryEncoder) Encode(value *CatalogEntry) enc.Wire {

	wire := make(enc.Wire, 1)
	wire[0] = make([]byte, encoder.Length)
	buf := wire[0]
	encoder.EncodeInto(value, buf)

	return wire
}

func (context *CatalogEntryParsingContext) Parse(reader enc.WireView, ignoreCritical bool) (*CatalogEntry, error) {

	var handled_FileName bool = false
	var handled_OwnerName bool = false
	var handled_ServerName bool = false

	progress := -1
	_ = progress

	value := &CatalogEntry{}
	var err error
	var startPos int
	for {
		startPos = reader.Pos()
		if startPos >= reader.Length() {
			break
		}
		typ := enc.TLNum(0)
		l := enc.TLNum(0)
		typ, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}
		l, err = reader.ReadTLNum()
		if err != nil {
			return nil, enc.ErrFailToParse{TypeNum: 0, Err: err}
		}

		err = nil
		if handled := false; true {
			switch typ {
			case 7685:
				if true {
					handled = true
					handled_FileName = true
					{
						var builder strings.Builder
						_, err = reader.CopyN(&builder, int(l))
						if err == nil {
							value.FileName = builder.String()
						}
					}
				}
			case 7686:
				if true {
					handled = true
					handled_OwnerName = true
					value.OwnerName, err = context.OwnerName_context.Parse(reader.Delegate(int(l)), ignoreCritical)
				}
			case 7687:
				if true {
					handled = true
					handled_ServerName = true
					value.ServerName, err = context.ServerName_context.Parse(reader.Delegate(int(l)), ignoreCritical)
				}
			default:
				if !ignoreCritical && ((typ <= 31) || ((typ & 1) == 1)) {
					return nil, enc.ErrUnrecognizedField{TypeNum: typ}
				}
				handled = true
				err = reader.Skip(int(l))
			}
			if err == nil && !handled {
			}
			if err != nil {
				return nil, enc.ErrFailToParse{TypeNum: typ, Err: err}
			}
		}
	}

	startPos = reader.Pos()
	err = nil

	if !handled_FileName && err == nil {
		err = enc.ErrSkipRequired{Name: "FileName", TypeNum: 7685}
	}
	if !handled_OwnerName && err == nil {
		value.OwnerName = nil
	}
	if !handled_ServerName && err == nil {
		value.ServerName = nil
	}

	if err != nil {
		return nil, err
	}

	return value, nil
}

func (value *CatalogEntry) Encode() enc.Wire {
	encoder := CatalogEntryEncoder{}
	encoder.Init(value)
	return encoder.Encode(value)
}

func (value *CatalogEntry) Bytes() []byte {
	return value.Encode().Join()
}

func ParseCatalogEntry(reader enc.WireView, ignoreCritical bool) (*CatalogEntry, error) {
	context := CatalogEntryParsingContext{}
	context.Init()
	return context.Parse(reader, ignoreCritical)
}
